# Generated by Django 3.0.3 on 2020-02-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LivePriceTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('volume', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_price', to='stockapp.Stock')),
            ],
            options={
                'unique_together': {('stock', 'time')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalPriceTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=16)),
                ('high', models.DecimalField(decimal_places=6, max_digits=16)),
                ('low', models.DecimalField(decimal_places=6, max_digits=16)),
                ('close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('volume', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_price', to='stockapp.Stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
